[".config/nvim"]
    type = "archive"
    url = "https://codeload.github.com/NvChad/NvChad/zip/refs/heads/v2.0"
    stripComponents = 1
    refreshPeriod = "168h"

[".config/zsh/plugins/zsh-vi-mode"]
    type = "git-repo"
    url = "https://github.com/audibleblink/zsh-vi-mode"

[".config/zsh/plugins/substring-search/substring-search.plugin.zsh"]
    type = "file"
    url = "https://raw.githubusercontent.com/zsh-users/zsh-history-substring-search/da5f067/zsh-history-substring-search.zsh"

[".config/zsh/plugins/autopair/autopair.plugin.zsh"]
    type = "file"
    url = "https://raw.githubusercontent.com/hlissner/zsh-autopair/34a8bca/autopair.zsh"

[".config/zsh/plugins/zsh-syntax-highlighting"]
    type = "archive"
    url = "https://github.com/zsh-users/zsh-syntax-highlighting/archive/refs/tags/0.8.0.tar.gz"
    exact = true
    stripComponents = 1

[".local/share/tmux/plugins/tpm"]
    type = "archive"
    url = "https://github.com/tmux-plugins/tpm/archive/refs/tags/v3.1.0.tar.gz"
    exact = true
    stripComponents = 1

[".config/kitty/themes"]
    type = "archive"
    url = "https://github.com/audibleblink/kitty-themes/archive/refs/heads/master.zip"
    exact = true
    stripComponents = 2
    path = "themes"
