[".config/nvim"]
    type = "archive"
    url = "https://codeload.github.com/NvChad/NvChad/zip/refs/heads/v2.0"
    stripComponents = 1
    refreshPeriod = "168h"

[".config/zsh/plugins/zsh-autopair"]
    type = "archive"
    url = "https://github.com/hlissner/zsh-autopair/archive/refs/tags/v1.0.tar.gz"
    exact = true
    stripComponents = 1

[".config/zsh/plugins/zsh-syntax-highlighting"]
    type = "archive"
    url = "https://github.com/zsh-users/zsh-syntax-highlighting/archive/refs/tags/0.8.0.tar.gz"
    exact = true
    stripComponents = 1

[".local/share/tmux/plugins/tpm"]
    type = "archive"
    url = "https://github.com/tmux-plugins/tpm/archive/refs/tags/v3.1.0.tar.gz"
    exact = true
    stripComponents = 1

{{ if (.dev) }}
[".local/share/gvm"]
    type = "archive"
    url = "https://github.com/moovweb/gvm/archive/dd652539fa4b771840846f8319fad303c7d0a8d2.zip"
    exact = true
    stripComponents = 1
{{ end }}


[".config/alacritty/themes"]
    type = "archive"
    url = "https://github.com/alacritty/alacritty-theme/archive/refs/heads/master.zip"
    exact = true
    stripComponents = 2
    path = "themes"


