general.import = [ "~/.config/omarchy/current/theme/alacritty.toml" ]

[env]
TERM = "xterm-256color"

[font]
normal = { family = "CodeliaLigatures Nerd Font" }
bold = { family = "CodeliaLigatures Nerd Font" }
italic = { family = "CodeliaLigatures Nerd Font" }
size = 9

[window]
padding.x = 2
padding.y = 1
dynamic_padding = true
decorations = "None"
opacity = 1

[keyboard]
bindings = [
{ key = "F11", action = "ToggleFullscreen" }
]
