live_config_reload = true

# Theme configuration
import = [ "~/.config/alacritty/bearded-arc.toml" ]
# import = [ "~/.config/alacritty/hackthebox.toml" ]
# import = [ "~/.config/alacritty/themes/catppuccin_mocha.toml" ]

[colors]
draw_bold_text_with_bright_colors = true

[window]
opacity = 0.95
blur = true
decorations = "buttonless"
option_as_alt = "OnlyRight"

[env]
TERM = "xterm-256color"

[font]
size = 16.0
#
[font.offset]
# x = -1
y = 1

# [font.glyph_offset]
# x = 2

[scrolling]
history = 50000
multiplier = 3

[font.normal]
family = "CodeliaLigatures Nerd Font"
style = "Regular"

[font.bold]
family = "CodeliaLigatures Nerd Font"
style = "Bold"

[font.italic]
family = "CodeliaLigatures Nerd Font"
style = "Italic"

[font.bold_italic]
family = "CodeliaLigatures Nerd Font"
style = "BoldItalic"

[window.padding]
x = 8
y = 4

[window.class]
instance = "Alacritty"
general = "Alacritty"

[[keyboard.bindings]]
key = "V"
mods = "Command"
action = "Paste"

[[keyboard.bindings]]
key = "C"
mods = "Command"
action = "Copy"

[[keyboard.bindings]]
key = "Insert"
mods = "Shift"
action = "PasteSelection"

[[keyboard.bindings]]
key = "Key0"
mods = "Control"
action = "ResetFontSize"

[[keyboard.bindings]]
key = "Equals"
mods = "Control"
action = "IncreaseFontSize"

[[keyboard.bindings]]
key = "Plus"
mods = "Control"
action = "IncreaseFontSize"

[[keyboard.bindings]]
key = "Minus"
mods = "Control"
action = "DecreaseFontSize"

[[keyboard.bindings]]
key = "Enter"
mods = "Command"
action = "ToggleFullscreen"

[[keyboard.bindings]]
key = "Paste"
mods = "None"
action = "Paste"

[[keyboard.bindings]]
key = "Copy"
mods = "None"
action = "Copy"

[[keyboard.bindings]]
key = "L"
mods = "Control"
action = "ClearLogNotice"

[[keyboard.bindings]]
key = "L"
mods = "Control"
chars = "\f"

[[keyboard.bindings]]
key = "PageUp"
mods = "None"
action = "ScrollPageUp"
mode = "~Alt"

[[keyboard.bindings]]
key = "PageDown"
mods = "None"
action = "ScrollPageDown"
mode = "~Alt"

[[keyboard.bindings]]
key = "Home"
mods = "Shift"
action = "ScrollToTop"
mode = "~Alt"

[[keyboard.bindings]]
key = "End"
mods = "Shift"
action = "ScrollToBottom"
mode = "~Alt"

