# bearded-arc colorscheme for alacritty
# by audibleblink, https://github.com/audibleblink/hackthebox.vim

# Default colors
[colors.primary]
background = "#1c2433"
foreground = "#8196b5" 

[colors.selection]
text = "#ffffff"
background = "#313f55"

[colors.cursor]
text = '#eee9fc'
cursor = '#eee9fc'

[colors.normal]
black = "#000000"
red = "#E35535"
green = "#3CEC85"
yellow = "#EACD61"
blue = "#69C3FF"
magenta = "#B78AFF"
cyan = "#2ee7b6"
white = "#ffffff"

[colors.bright]
black = "#666666"
red = "#FF738A"
green = "#A4EF58"
yellow = "#ffcc5c"
blue = "#5cb2ff"
magenta = "#F38CEC"
cyan = "#22ECDB"
white = "#ffffff"
