device_name = "AT Translated Set 2 keyboard"
# If you have multiple devices with the same name, you can optionally
# specify the `phys` value that is printed by the `list-devices` subcommand
# phys = "usb-0000:07:00.3-2.1.1/input0"

[[dual_role]]
input = "KEY_CAPSLOCK"
hold = ["KEY_LEFTCTRL"]
tap = ["KEY_ESC"]

[[dual_role]]
input = "KEY_LEFTSHIFT"
hold = ["KEY_LEFTSHIFT"]
tap = ["KEY_KPLEFTPAREN"]

[[dual_role]]
input = "KEY_RIGHTSHIFT"
hold = ["KEY_RIGHTSHIFT"]
tap = ["KEY_KPRIGHTPAREN"]
