tick_rate = 50
default_channel = "files"

history_size = 10
global_history = false

[ui]
use_nerd_font_icons = true
ui_scale = 90
input_bar_position = "bottom"
orientation = "landscape"
theme = "catppuccin"
preview_size = 60

[ui.features]
preview_panel = { enabled = true, visible = true }
help_panel = { enabled = false, visible = false }
status_bar = { enabled = false, visible = false }
remote_control = { enabled = true, visible = false }

[ui.preview_panel]
size = 60
scrollbar = true

[shell_integration.channel_triggers]
"git-status" = ["git add", "ga"]
"dirs" = ["cd", "ls", "rmdir"]
"files" = ["mv", "cp", "nvim", "e"]
